credentials:
  usernames:
    admin:
      email: jsmith@gmail.com
      first_name: John
      last_name: Smith
      password: abc  # Либо пароль в открытом виде, либо его SHA256-хеш

cookie:
  name: your_cookie_name
  expiry_days: 30
  key: your_cookie_key
