name: CI/CD Streamlit App

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  build-test-deploy:
    runs-on: ubuntu-latest
    timeout-minutes: 90

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      # - name: Build and test container locally
      #   timeout-minutes: 90      
      #   run: |
      #     docker buildx build --progress=plain --load --no-cache -t test-streamlit .
      #     docker run -d -p 8501:8501 --name test-app test-streamlit
      #     sleep 10
      #     curl --fail http://localhost:8501/_stcore/health
      #     docker stop test-app
      #     docker rm test-app

      - name: Deploy to Yandex VM via SSH
        timeout-minutes: 90      
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.VM_IP }}
          username: ${{ secrets.VM_USER }}
          key: ${{ secrets.VM_SSH_KEY }}
          passphrase: ${{ secrets.VM_PASSPHRASE }}
          port: ${{ secrets.VM_SSH_PORT }}
        script: |
          set -e
          docker stop app || true
          docker rm app || true
          cd /home/${{ secrets.VM_USER }}
          rm -rf builder_project_dash || true
          git clone git@github.com:JustAnllusion/builder_project_dash.git
          cd builder_project_dash
          echo "[`date`] Starting remote Docker build"
          docker build --pull --no-cache -t streamlit-app .
          echo "[`date`] Remote Docker build completed"
          docker run -d --name app -p 8501:8501 streamlit-app